import { spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { isAbsolute, resolve } from "node:path";
import { RememberServer } from "./remember-server.js";
import type { GenerateOptions, ModelRuntime } from "./types.js";

export interface PsmModelRuntimeOptions {
  checkpoint: string;
  python?: string;
  repoRoot?: string;
  outputFormat?: "tagged" | "json" | "at_tag";
  device?: string;
  maxNewTokens?: number;
}

function resolveRepoRoot(explicit?: string): string {
  if (explicit) return resolve(explicit);
  const cwd = process.cwd();
  if (existsSync(resolve(cwd, "psm-model", "src", "psm_model"))) return cwd;
  return cwd;
}

function extractStoragePayload(prompt: string): Record<string, unknown> | null {
  const assistantIdx = prompt.lastIndexOf("<|assistant|>");
  const userIdx = prompt.lastIndexOf("<|user|>");
  if (userIdx < 0 || assistantIdx <= userIdx) return null;
  const chunk = prompt.slice(userIdx, assistantIdx);
  // buildStoragePrompt embeds schema examples with `{` before the real JSON payload line.
  for (const line of chunk.split("\n").reverse()) {
    const trimmed = line.trim();
    if (!trimmed.startsWith("{") || !trimmed.endsWith("}")) continue;
    try {
      const parsed = JSON.parse(trimmed) as unknown;
      if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) continue;
      const payload = parsed as Record<string, unknown>;
      const operation = payload.operation;
      if (
        "conversation" in payload
        || operation === "remember_llm_response"
        || operation === "repair_remember_json"
      ) {
        return payload;
      }
    } catch {
      continue;
    }
  }
  return null;
}

function normalizeDecision(parsed: Record<string, unknown>): string {
  const memory = parsed.memory;
  const facts = Array.isArray(parsed.facts) ? parsed.facts : [];
  const normalizedFacts = facts.map((fact) => {
    if (!fact || typeof fact !== "object" || Array.isArray(fact)) return fact;
    const row = { ...(fact as Record<string, unknown>) };
    if (row.value !== undefined && row.value_text === undefined && typeof row.value === "string") {
      row.value_text = row.value;
    }
    return row;
  });
  return JSON.stringify({
    action: parsed.action,
    memory: memory ?? null,
    facts: normalizedFacts,
    reasoning: parsed.reasoning ?? "Generated by psm-model decoder.",
    confidence: parsed.confidence,
    emotional_weight: parsed.emotional_weight,
    contradiction_score: parsed.contradiction_score
  });
}

export class PsmModelRuntime implements ModelRuntime {
  private readonly checkpoint: string;
  private readonly python: string;
  private readonly repoRoot: string;
  private readonly outputFormat: "tagged" | "json" | "at_tag";
  private readonly device: string;
  private readonly maxNewTokens: number;

  constructor(options: PsmModelRuntimeOptions) {
    this.checkpoint = resolve(options.checkpoint);
    this.python = options.python ?? (process.platform === "win32" ? ".venv\\Scripts\\python.exe" : ".venv/bin/python");
    this.repoRoot = resolveRepoRoot(options.repoRoot);
    this.outputFormat = options.outputFormat ?? "tagged";
    this.device = options.device ?? "auto";
    this.maxNewTokens = options.maxNewTokens ?? Number(process.env.PSM_MAX_NEW_TOKENS ?? 384);
  }

  private runtimeEnv(): NodeJS.ProcessEnv {
    return {
      ...process.env,
      PYTHONPATH: resolve(this.repoRoot, "psm-model", "src"),
      PSM_FORCE_CPU: process.env.PSM_FORCE_CPU ?? (process.env.PSM_RUNPOD === "1" ? "0" : "1")
    };
  }

  private rememberServer(): RememberServer {
    return RememberServer.get({
      python: this.python,
      checkpoint: this.checkpoint,
      repoRoot: this.repoRoot,
      outputFormat: this.outputFormat,
      device: this.device,
      maxNewTokens: this.maxNewTokens,
      env: this.runtimeEnv()
    });
  }

  async warmup(): Promise<void> {
    if (process.env.PSM_REMEMBER_SERVER === "0") return;
    await this.rememberServer().ensureReady();
  }

  private async generateViaServer(payload: Record<string, unknown>): Promise<Record<string, unknown>> {
    return this.rememberServer().remember(payload);
  }

  async generateJson(prompt: string, _options: GenerateOptions = {}): Promise<string> {
    const payload = extractStoragePayload(prompt);
    if (!payload) {
      throw new Error("PsmModelRuntime only supports PSM storage prompts from remember().");
    }
    if (process.env.PSM_REMEMBER_SERVER !== "0") {
      const report = await this.generateViaServer(payload);
      if (!report.parsed || typeof report.parsed !== "object") {
        throw new Error(`psm-model returned no storage decision: ${JSON.stringify(report)}`);
      }
      return normalizeDecision(report.parsed as Record<string, unknown>);
    }
    const pythonPath = isAbsolute(this.python) ? this.python : resolve(this.repoRoot, this.python);
    const env = this.runtimeEnv();
    const result = spawnSync(
      pythonPath,
      [
        "-m",
        "psm_model.remember_cli",
        this.checkpoint,
        "--output-format",
        this.outputFormat,
        "--device",
        this.device,
        "--max-new-tokens",
        String(this.maxNewTokens)
      ],
      {
        cwd: this.repoRoot,
        env,
        input: JSON.stringify(payload),
        encoding: "utf8",
        maxBuffer: 10 * 1024 * 1024
      }
    );
    if (result.error) {
      throw result.error;
    }
    const stdout = result.stdout?.trim() ?? "";
    const stderr = result.stderr?.trim() ?? "";
    if (result.status !== 0) {
      throw new Error(stdout || stderr || `psm_model.remember_cli failed with status ${result.status}`);
    }
    const report = JSON.parse(stdout) as { parsed?: Record<string, unknown> };
    if (!report.parsed) {
      throw new Error(`psm-model returned no storage decision: ${stdout}`);
    }
    return normalizeDecision(report.parsed);
  }
}

export class HybridPsmRuntime implements ModelRuntime {
  constructor(
    private readonly primary: ModelRuntime,
    private readonly storage: PsmModelRuntime
  ) {}

  async warmup(): Promise<void> {
    await this.storage.warmup();
  }

  async generateJson(prompt: string, options: GenerateOptions = {}): Promise<string> {
    if (extractStoragePayload(prompt)) {
      return this.storage.generateJson(prompt, options);
    }
    return this.primary.generateJson(prompt, options);
  }
}
